import { jsPDF } from 'jspdf'

type Modality = 'mri' | 'ct' | 'fusion'

type Probability = {
  label: string
  probability: number
}

type ReportSection = {
  title: string
  body: string
}

type PredictionResponse = {
  modality: Modality
  predicted_label: string
  confidence: number
  probabilities: Probability[]
  report: ReportSection[]
  notes: string[]
}

type ExportOptions = {
  generatedAt: Date
  patientName?: string
  authorName: string
}

function formatLabel(label: string) {
  return label.replaceAll('_', ' ')
}

function buildFilename(result: PredictionResponse) {
  const safeLabel = result.predicted_label.replaceAll('_', '-')
  return `neurovision-${result.modality}-${safeLabel}-report.pdf`
}

export function exportReportPdf(result: PredictionResponse, options: ExportOptions) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const marginX = 52
  const topY = 52
  const maxTextWidth = pageWidth - marginX * 2
  const lineHeight = 16
  const sectionGap = 18
  let cursorY = topY

  const addFooter = () => {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(92, 106, 120)
    doc.text(`Generated by NeuroVision | Designed and built by ${options.authorName}`, marginX, pageHeight - 28)
  }

  const addPageIfNeeded = (requiredHeight: number) => {
    if (cursorY + requiredHeight <= pageHeight - 48) {
      return
    }

    addFooter()
    doc.addPage()
    cursorY = topY
  }

  const writeWrapped = (text: string, fontSize = 11, color: [number, number, number] = [44, 57, 70]) => {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(fontSize)
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, maxTextWidth)
    addPageIfNeeded(lines.length * lineHeight + 4)
    doc.text(lines, marginX, cursorY)
    cursorY += lines.length * lineHeight
  }

  const writeSection = (title: string, body: string) => {
    addPageIfNeeded(42)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(17, 35, 49)
    doc.text(title.toUpperCase(), marginX, cursorY)
    cursorY += 18
    writeWrapped(body)
    cursorY += sectionGap
  }

  const rankedProbabilities = [...result.probabilities].sort((left, right) => right.probability - left.probability)
  const generatedAtLabel = options.generatedAt.toLocaleString('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })
  const patientLabel = options.patientName?.trim() || 'Not provided'

  doc.setFillColor(14, 40, 56)
  doc.rect(0, 0, pageWidth, 92, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(241, 248, 252)
  doc.text('NeuroVision Clinical Summary', marginX, 42)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text('AI-assisted structured report for brain imaging review', marginX, 62)

  cursorY = 118
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(17, 35, 49)
  doc.text('Report Metadata', marginX, cursorY)
  cursorY += 20

  writeWrapped(`Patient / study label: ${patientLabel}`)
  writeWrapped(`Generated: ${generatedAtLabel}`)
  writeWrapped(`Workflow: ${result.modality.toUpperCase()}`)
  writeWrapped(`Top classification: ${formatLabel(result.predicted_label)}`)
  writeWrapped(`Model confidence: ${(result.confidence * 100).toFixed(1)}%`)
  cursorY += sectionGap

  writeSection(
    'Probability Summary',
    rankedProbabilities
      .map((entry, index) => `${index + 1}. ${formatLabel(entry.label)} - ${(entry.probability * 100).toFixed(1)}%`)
      .join('\n'),
  )

  for (const section of result.report) {
    writeSection(section.title, section.body)
  }

  if (result.notes.length) {
    writeSection('Operational Notes', result.notes.map((note, index) => `${index + 1}. ${note}`).join('\n'))
  }

  writeSection(
    'Clinical Use Statement',
    'This document is generated from the NeuroVision research prototype for decision support and structured communication only. It does not replace complete multi-sequence image review, formal radiology reporting, pathology correlation, or clinician judgment.',
  )

  addFooter()
  doc.save(buildFilename(result))
}
